# Generated by Django 5.0.6 on 2024-08-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0003_booking_delete_travels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='Name',
        ),
    ]
