# Generated by Django 5.0.6 on 2024-08-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0004_rename_name_booking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Name',
            new_name='uname',
        ),
    ]
