# Generated by Django 5.0.6 on 2024-08-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0006_rename_uname_booking_u_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='checkin',
            new_name='From',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='u_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='checkout',
            new_name='To',
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MS.destination'),
        ),
    ]
