# Generated by Django 5.0.6 on 2024-08-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='travels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=225)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
